import { Container } from 'components/Container/Container.styled';
import Baner from 'components/Baner/Baner';
import { AddSharp } from '../assets/img/icons/Icons';
import {
  AboutDescription,
  AboutImg,
  AboutSection,
  AboutTitle,
  IconWrapper,
  SecondPartWrapper,
  TitleWrapper,
} from './About.styled';
import DeskImg1x from '../assets/img/about-img-deck.png';
import DeskImg2x from '../assets/img/about-img-deck@2.png';
import TabImg1x from '../assets/img/about-img-tab.png';
import TabImg2x from '../assets/img/about-img-tab@2.png';
import MobImg1x from '../assets/img/about-img-mob.png';
import MobImg2x from '../assets/img/about-img-mob@2.png';

function About() {
  return (
    <AboutSection id="about">
      <Container>
        <TitleWrapper>
          <AboutTitle>
            a Story that started with{' '}
            <span>
              one simple <br />
              ape
            </span>
          </AboutTitle>
          <AboutDescription>
            WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
            THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE <br />
            YACHT
          </AboutDescription>
        </TitleWrapper>
        <SecondPartWrapper>
          <IconWrapper>
            <AddSharp />
            <p>
              EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
              ARE RANDOMLY GENERATED BY USERS
            </p>
          </IconWrapper>
          <AboutImg>
            <source
              media="(min-width: 1280px)"
              srcSet={`
          ${DeskImg1x} 1x,
          ${DeskImg2x} 2x
        `}
              width="492"
              height="662"
            />
            <source
              media="(min-width: 768px)"
              srcSet={`
          ${TabImg1x} 1x,
          ${TabImg2x} 2x
        `}
              width="313"
              height="422"
            />
            <source
              media="(max-width: 767px)"
              srcSet={`
          ${MobImg1x} 1x,
          ${MobImg2x} 2x
        `}
            />
            <img src={DeskImg1x} alt="monkey wearing glasses" loading="lazy" />
          </AboutImg>
        </SecondPartWrapper>
        <Baner />
      </Container>
    </AboutSection>
  );
}

export default About;
